Ios py bastion
oracle-devrel/technology-engineering pull request #1509
Opened 2024-11-29 07:26 UTC by bios62

Created new version of the bastion script, based on python, to be OS independent, and added flexibility for easier usage. Getting OCI users to understand the importance of Bastion service over jump server is important

2025-02-25 13:10 UTC, oheimburger requested changes

2025-02-25 13:10 UTC, oheimburger commented on security/security-design/shared-assets/bastion-py-script/files/sample.json
> +
Remove empty lines.

2025-02-25 13:10 UTC, oheimburger commented on security/security-design/shared-assets/bastion-py-script/files/bastionsession.py
> +"""Bastion Service script
Add a Copyright notice.

2025-02-25 13:10 UTC, oheimburger commented on security/security-design/shared-assets/bastion-py-script/files/bastionsession.py
> +        if session_config[const.SSHCOMMAND] == const.SSH:
This can be a security issue. Use fully qualified path.

2025-02-25 13:10 UTC, oheimburger commented on security/security-design/shared-assets/bastion-py-script/files/bastionsession.py
> +                "putty -i "
This can be a security issue. Use fully qualified path.

2025-02-25 13:10 UTC, oheimburger commented on security/security-design/shared-assets/bastion-py-script/files/bastionsession.py
> +"""Bastion Service script
Generally, speaking it is considered a good practice to use f.strings instead of C-style strings in Python (https://fstring.help/cheat/)

2025-02-25 13:10 UTC, oheimburger commented on security/security-design/shared-assets/bastion-py-script/files/bastionsession.py
> +"""Bastion Service script
Check the code against flake8 (e.g., using the VS Code plugin).

2025-02-26 20:26 UTC, bios62 commented on security/security-design/shared-assets/bastion-py-script/LICENSE
Fixed

2025-02-26 20:26 UTC, bios62 commented on security/security-design/shared-assets/bastion-py-script/README.md
> +- python 3.8 or above (latest patch version)
changed

2025-02-26 20:27 UTC, bios62 commented on security/security-design/shared-assets/bastion-py-script/README.md
> +Copyright (c) 2024 Oracle and/or its affiliates.
corrected

2025-02-26 20:27 UTC, bios62 commented on security/security-design/shared-assets/bastion-py-script/files/constants.py
> +
corrected

2025-02-26 20:30 UTC, bios62 commented on security/security-design/shared-assets/bastion-py-script/files/__pycache__/constants.cpython-310.pyc
Absolutely!, fixed .gitignore locally

2025-02-26 21:39 UTC, bios62 commented on security/security-design/shared-assets/bastion-py-script/files/bastionsession.py
> +"""Bastion Service script
Fixed

2025-02-26 21:42 UTC, bios62 commented on security/security-design/shared-assets/bastion-py-script/files/bastionsession.py
> +                "putty -i "
It changes the generated output from the sdk. The sdk generates without path, and it is a printed command the user copy/paste

2025-02-27 06:13 UTC, bios62 commented on security/security-design/shared-assets/bastion-py-script/files/bastionsession.py
> +        if session_config[const.SSHCOMMAND] == const.SSH:
The command is generated by the SDK without path. The command is used for the new ssh command output from. the script, following the structure of teh command comming from the SDK. It is defined in the configfile, if it is not set, it will be the as the one genereated by the SDK.

2025-03-25 13:21 UTC, oheimburger requested changes

2025-03-25 13:21 UTC, oheimburger commented on security/security-design/shared-assets/bastion-py-script/LICENSE
> +Copyright (c) 2024 Oracle and/or its affiliates.
Update copyright year.

2025-03-25 13:21 UTC, oheimburger commented on security/security-design/shared-assets/bastion-py-script/files/constants.py
> +BASTIONCONFIG = "bastionconfig"
Insert copyright line.

2025-03-25 13:21 UTC, oheimburger commented on security/security-design/shared-assets/bastion-py-script/files/bastionsession.py
> +
Insert copyright line.

2025-03-25 13:22 UTC, AlexanderHodicke commented
PR includes faulty commit in the branch - we need to reject and delete the branch. You need to please create anew branch on your device, add the cleaned files, and commit and create a new PR.

2025-04-01 12:47 UTC, oheimburger approved these changes

2025-04-01 12:48 UTC, merged