fbo_oci_backup_inspector
oracle-devrel/technology-engineering pull request #170
Opened 2023-07-06 07:28 UTC by Olygo

commit = 1

2023-07-06 08:16 UTC, Olygo commented
I have read the CLA Document and I hereby sign the CLA

2023-07-06 09:20 UTC, AlexanderHodicke requested changes
Code review

Rest is good

2023-07-06 09:20 UTC, AlexanderHodicke commented on cloud-infrastructure/compute-including-hpc/compute/python_scripts/OCI-BackupInspector/OCI-BackupInspector.py
@oheimburger  Please review

2023-07-11 08:12 UTC, oheimburger commented on cloud-infrastructure/compute-including-hpc/compute-software/python_scripts/OCI-BackupInspector/modules/utils.py
> +                fieldnames=[
Duplication of code. Consolidate.

2023-07-11 10:24 UTC, closed without merging