Created md file containing link to asset
oracle-devrel/technology-engineering pull request #20
Opened 2023-06-27 18:34 UTC by gianniconte

Issuing my first pull request

2023-06-27 18:41 UTC, gianniconte commented
I have read the CLA Document and I hereby sign the CLA

2023-06-28 09:40 UTC, AlexanderHodicke requested changes
I assume this is just a link change on a product page. No need for a new asset folder. Please change / or write me if I misunderstood something.

2023-06-28 11:43 UTC, gianniconte commented
Hi Alexander.

It is not an asset. It is a link to a video demo.

It was first attempt, so I will do better accordingly.

Gianni

[cid:ce47353a-44c1-4da5-bb4f-6307c7468cf3]
Giovanni Conte
Specialist - Integration
[cid:f3619dc8-6e62-4cc4-a261-094db4872c1e]
Oracle Certified Professional
- Oracle Cloud Infrastructure (OCI)
- Cloud Platform Application Integration
Mobile: +39 348 1546002
Oracle Italy

[cid:4bf237d2-6259-4aa4-b951-10788cbaac19]

Oracle is committed to developing practices and products that help protect the environment
________________________________
Da: Alexander Hödicke ***@***.***>
Inviato: mercoledì 28 giugno 2023 11:41
A: oracle-devrel/technology-engineering ***@***.***>
Cc: Giovanni Conte ***@***.***>; Author ***@***.***>
Oggetto: [External] : Re: [oracle-devrel/technology-engineering] Created md file containing link to asset (PR #20)


@AlexanderHodicke requested changes on this pull request.

I assume this is just a link change on a product page. No need for a new asset folder. Please change / or write me if I misunderstood something.

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/oracle-devrel/technology-engineering/pull/20*pullrequestreview-1502697607__;Iw!!ACWV5N9M2RV99hQ!OxdqUf_evIZN_Iaz8i3S88c_YrwT8VoKtQfnqHWA_9kZQ4y_dGAKlcIsxNGXBJ69iJGBbulMMLBSOUxUOl9fZ7VBgpD7$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/BA352UFSKRJBXIXXVXN45P3XNP33JANCNFSM6AAAAAAZV7UYKE__;!!ACWV5N9M2RV99hQ!OxdqUf_evIZN_Iaz8i3S88c_YrwT8VoKtQfnqHWA_9kZQ4y_dGAKlcIsxNGXBJ69iJGBbulMMLBSOUxUOl9fZ8M7_xrq$>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-06-28 14:23 UTC, MarcelStraka commented on application-development/application-integration-and-process-automation/oracle-integration-cloud/OIC - Recipes and Accelerators - Exploit Reuse/files/README.md
Why do we have this folder?

2023-06-29 07:23 UTC, AlexanderHodicke commented
PII information is found in the PR comment (business phone number) I have to reject and delete the branch. Please create a new branch and PR. Please use your web browser to reply through emails.

2023-06-29 07:23 UTC, closed without merging