Gbu initial
oracle-devrel/technology-engineering pull request #276
Opened 2023-07-18 19:48 UTC by oradscarlin

2023-07-19 14:32 UTC, velrajkuppu commented on cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail-gbu/README.md
Please can we point the Certification Matrix URL from docs.oracle... if available rather than (https://support.oracle.com/epmos/faces/DocumentDisplay?id=857142.1) as users need a login to access this information?

2023-07-19 14:33 UTC, velrajkuppu commented on cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail-gbu/rms-decision-tree/README.md
[asset preview](https://raw.githack.com/oracle-devrel/technology-engineering/main/cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail-gbu/rms-decision-tree/files/rms-decision-tree.html)

Above URL doesn't work, get 404 error!

2023-07-19 14:35 UTC, velrajkuppu requested changes
Please review individual comments and fix

2023-07-19 14:49 UTC, oradscarlin commented on cloud-architecture/oracle-apps-hyperion-siebel-gbu/gbu/retail-gbu/README.md
Unfortunately that document is not available on docs.oracle.com, only on MOS. Login to MyOracleSupport website should not be a problem assuming that whoever is looking for specific Oracle workload documentation already has an Oracle account.

2023-07-20 10:02 UTC, velrajkuppu approved these changes

2023-07-20 10:02 UTC, merged