WADs and Solution Defintions and Solution Designs created for Github publication
oracle-devrel/technology-engineering pull request #322
Opened 2023-07-28 13:20 UTC by DoubleUP66

WADs and Solution Defintions and Solution Designs created for Github publication.

Because of the work done for future split in Solution Definition and Solution Design I have used those create the external versions

2023-07-31 12:02 UTC, DoubleUP66 commented
Changed some files to anonymize content

2023-08-01 11:09 UTC, josecrcruz requested changes

2023-08-01 11:09 UTC, josecrcruz commented on data-platform/analytical-data-platform-lakehouse/workload-architecture-documents/obiee-db-migration-to-oac-adw/SolutionDefinition/SolutionDefinition
This isn't rendering as an md file.

2023-08-01 11:10 UTC, josecrcruz commented
Need to have the license.txt and readme.md files on each workload directory. There is also an md file that isn't rendering.
Can you please have a look? Thanks.

2023-08-01 15:07 UTC, josecrcruz approved these changes

2023-08-01 15:07 UTC, merged