created okv monitor corrected structure for integ
oracle-devrel/technology-engineering pull request #381
Opened 2023-08-30 13:03 UTC by mfioramo

please review

2023-09-01 12:25 UTC, AlexanderHodicke reviewed
A code review by @oheimburger is needed. The rest looks fine.

2023-09-01 12:25 UTC, AlexanderHodicke commented on manageability-and-operations/operations-advisory/okv-monitoring/files/main.go
@oheimburger please review

2023-09-04 07:27 UTC, oheimburger requested changes
Code contains passwords and branch must be deleted.
Before submitting a new version, review the other comments, too.

2023-09-04 07:27 UTC, oheimburger commented on manageability-and-operations/operations-advisory/okv-monitoring/README.md
> +5. Run the program as go run main.go -target="okv_ip" -Port=161 -UserName="okv_snmp_user" -AuthenticationPassphrase="okv_snmp_user" -PrivacyPassphrase="okv_snmp_user"
Make sure that command line can be distinguished from normal text, like "run ```go run main.go```"

2023-09-04 07:27 UTC, oheimburger commented on manageability-and-operations/operations-advisory/okv-monitoring/files/main.go
> +			AuthenticationPassphrase: "Welcome123.",
Password! Branch needs to be deleted.

2023-09-04 07:27 UTC, oheimburger commented on manageability-and-operations/operations-advisory/okv-monitoring/files/main.go
> +			PrivacyPassphrase:        "Welcome123.",
Password! Branch needs to be deleted.

2023-09-04 07:27 UTC, oheimburger commented on manageability-and-operations/operations-advisory/okv-monitoring/files/main.go
> +	/*
Commented code should not be present in GitHub. Remove.

2023-09-04 07:27 UTC, oheimburger commented on manageability-and-operations/operations-advisory/okv-monitoring/files/main.go
> +	//err = params.BulkWalk(".1.3.6.1.4.1.2021.2", printValue)
Commented code should not be present in GitHub. Remove.

2023-09-04 07:27 UTC, oheimburger commented on manageability-and-operations/operations-advisory/okv-monitoring/files/main.go
> +/*
Commented code should not be present in GitHub. Remove.

2023-09-04 07:27 UTC, oheimburger commented on manageability-and-operations/operations-advisory/okv-monitoring/files/main.go
> +// a very simple snmp okv crawler
Use common English grammar and punctuation!

2023-09-04 12:16 UTC, closed without merging