Added SD template
oracle-devrel/technology-engineering pull request #398
Opened 2023-09-04 14:04 UTC by AlexanderHodicke

2023-09-05 07:04 UTC, oheimburger requested changes

2023-09-05 07:04 UTC, oheimburger commented on others/customer-documentation/solution-definition-mandatory/files/solution-definition_mandatory.md
- Table in Mandatory Security Best Practices is broken. Please review.
- Naming Convention should be a chapter of it's own. It is not security related nor part of any architecture blueprint.
- Why a chapter for "Security and Identity Management" and "Mandatory Security Best Practices"? "Mandatory Security Best Practices" is meant to replace "Security and Identity Management"

2023-09-05 07:04 UTC, oheimburger commented on others/customer-documentation/solution-definition-complete/files/solution-definition.md
- Table in Mandatory Security Best Practices is broken. Please review.
- Naming Convention should be a chapter of it's own. It is not security related nor part of any architecture blueprint.
- Why a chapter for "Security and Identity Management" and "Mandatory Security Best Practices"? "Mandatory Security Best Practices" is meant to replace "Security and Identity Management"

2023-09-07 13:34 UTC, AlexanderHodicke commented on others/customer-documentation/solution-definition-complete/files/solution-definition.md
- Done
- We agreed to leave it in LZ for now
- We will review this in a future iteration 

All done

2023-09-07 13:34 UTC, AlexanderHodicke commented on others/customer-documentation/solution-definition-mandatory/files/solution-definition_mandatory.md
Same as above

2023-09-07 13:42 UTC, oheimburger approved these changes
Assuming changes will applied in the next iteration.
Approved

2023-09-07 13:43 UTC, merged