tip of the day
oracle-devrel/technology-engineering pull request #520
Opened 2023-10-27 09:21 UTC by javidel

2023-11-03 16:04 UTC, AlexanderHodicke commented on data-platform/autonomous-database/autonomous-json/mongodb-compatibility-advisor-19c/report_advisor.txt
@oheimburger please review

2023-11-06 10:22 UTC, oheimburger requested changes

2023-11-06 10:22 UTC, oheimburger commented on data-platform/autonomous-database/autonomous-serverless/README.md
> +- [Tip 1](https://www.linkedin.com/posts/javier-de-la-torre-medina_oracle-autonomousdatabase-tipoftheday-activity-7104394940436164609-LSa-?utm_source=share&utm_medium=member_desktop)
This applies to all tips:

- Did you get a legal approval to use these non-Oracle resources?
- Remove all "utm_" query parameters

2023-11-06 10:25 UTC, javidel commented
Hi Olaf,

The content was created by me, using the tool Canva. My director Kristian Toms asked me to upload the videos there. If this answer the legal part, I will modify the links.

Thanks!
Javi

[Oracle]<http://www.oracle.com/>
Javier de la Torre, Principal Data Management Cloud Specialist
Mobile: +34 617 365 860
Specialist Cloud Engineering
Parque Tecnológico de Andalucía, C/Severo Ochoa 55 Campanillas

From: oheimburger ***@***.***>
Sent: Monday, November 6, 2023 11:23 AM
To: oracle-devrel/technology-engineering ***@***.***>
Cc: Javier de la Torre Medina ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [oracle-devrel/technology-engineering] tip of the day (PR #520)


@oheimburger requested changes on this pull request.

________________________________

In data-platform/autonomous-database/autonomous-serverless/README.md<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/520*discussion_r1383072772__;Iw!!ACWV5N9M2RV99hQ!MZE9ozuTEpb6oyTDcuP4OBo2v6gT5HThpBqfFIT7M4bgQnSYoMN5y6U_SyLNG63MriBFG6Yg3jUuGZZqvMniTnhWWQFycEpNhQ$>:

> @@ -25,6 +28,68 @@ Oracle Cloud provides a set of data management services built on self-driving Or



 - [Manage and Monitor Autonomous Database](https://apexapps.oracle.com/pls/apex/r/dbpm/livelabs/view-workshop?wid=553&clear=RR,180&session=115113440340155)

     - Complete the course about how to administrate an Autonomous Database.

+

+# Tip of the Day

+

+- [Tip 1](https://www.linkedin.com/posts/javier-de-la-torre-medina_oracle-autonomousdatabase-tipoftheday-activity-7104394940436164609-LSa-?utm_source=share&utm_medium=member_desktop<https://urldefense.com/v3/__https:/www.linkedin.com/posts/javier-de-la-torre-medina_oracle-autonomousdatabase-tipoftheday-activity-7104394940436164609-LSa-?utm_source=share&utm_medium=member_desktop__;!!ACWV5N9M2RV99hQ!MZE9ozuTEpb6oyTDcuP4OBo2v6gT5HThpBqfFIT7M4bgQnSYoMN5y6U_SyLNG63MriBFG6Yg3jUuGZZqvMniTnhWWQGibHTyhw$>)

This applies to all tips:

  *   Did you get a legal approval to use these non-Oracle resources?
  *   Remove all "utm_" query parameters

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/520*pullrequestreview-1714741973__;Iw!!ACWV5N9M2RV99hQ!MZE9ozuTEpb6oyTDcuP4OBo2v6gT5HThpBqfFIT7M4bgQnSYoMN5y6U_SyLNG63MriBFG6Yg3jUuGZZqvMniTnhWWQFkq5VXNA$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/AGL2X7TR2WGB4X6BWPUPVD3YDC27VAVCNFSM6AAAAAA6SQLCLGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMJUG42DCOJXGM__;!!ACWV5N9M2RV99hQ!MZE9ozuTEpb6oyTDcuP4OBo2v6gT5HThpBqfFIT7M4bgQnSYoMN5y6U_SyLNG63MriBFG6Yg3jUuGZZqvMniTnhWWQFNcfmE6w$>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2023-11-13 14:49 UTC, AlexanderHodicke approved these changes

2023-11-13 14:52 UTC, AlexanderHodicke approved these changes

2023-11-13 14:53 UTC, AlexanderHodicke approved these changes

2023-11-13 14:54 UTC, merged