Add files via upload
oracle-devrel/technology-engineering pull request #54
Opened 2023-06-29 11:46 UTC by witold-swierzy

2023-06-29 11:47 UTC, witold-swierzy commented
I have read the CLA Document and I hereby sign the CLA

2023-06-30 06:39 UTC, AlexanderHodicke commented
Next time, please add your Manager as a reviewer

2023-06-30 06:42 UTC, AlexanderHodicke commented on data-platform/core-converged-db/OracleJDBC23cNewFeatures/README.md
can you please rename the folder to lowercase with - example:  oracle-jdbc-23c-new-features

2023-06-30 06:44 UTC, AlexanderHodicke requested changes

2023-06-30 06:44 UTC, AlexanderHodicke commented on data-platform/core-converged-db/OracleJDBC23cNewFeatures/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
@oheimburger code review please

2023-06-30 06:44 UTC, AlexanderHodicke commented on data-platform/core-converged-db/OracleJDBC23cNewFeatures/src/jdb23cnfcdemotable.sql
> +drop table if exists test;
@oheimburger code review please

2023-06-30 06:44 UTC, AlexanderHodicke commented on data-platform/core-converged-db/OracleJDBC23cNewFeatures/src/main/java/swierzy/oraclejdbc23newfeatures/DMLSubscriber.java
> +package swierzy.oraclejdbc23newfeatures;
@oheimburger code review, please

File name and folder maybe strange.

2023-06-30 06:44 UTC, AlexanderHodicke commented on data-platform/core-converged-db/OracleJDBC23cNewFeatures/src/main/java/swierzy/oraclejdbc23newfeatures/Main.java
> +package swierzy.oraclejdbc23newfeatures;
@oheimburger code review please

2023-06-30 06:44 UTC, AlexanderHodicke commented on data-platform/core-converged-db/OracleJDBC23cNewFeatures/src/main/java/swierzy/oraclejdbc23newfeatures/QuerySubscriber.java
> +package swierzy.oraclejdbc23newfeatures;
@oheimburger code review please

2023-06-30 06:53 UTC, JesusGitHubOracle reviewed
Hi Alex - noted.

2023-06-30 07:09 UTC, oheimburger commented on data-platform/core-converged-db/OracleJDBC23cNewFeatures/README.md
This looks like a duplicate of PR 53.
I would reject this.

2023-06-30 07:10 UTC, oheimburger requested changes
Looks like a duplicate of PR 53.

2023-12-15 11:01 UTC, closed without merging