fixed title page and copyright year
oracle-devrel/technology-engineering pull request #61
Opened 2023-06-29 13:54 UTC by PeterObertTCE

fixed title page and copyright year

2023-06-29 14:03 UTC, MarcelStraka requested changes

2023-06-29 14:03 UTC, MarcelStraka commented on application-development/application-integration-and-process-automation/oracle-integration-cloud/01-oic-connectivity-agent/OIC-Connectivity-Agent-and-Hybrid-Integrations.pdf
The copyrights still need fixing

2023-06-30 08:28 UTC, AlexanderHodicke requested changes

2023-06-30 08:28 UTC, AlexanderHodicke commented on application-development/application-integration-and-process-automation/oracle-integration-cloud/01-oic-connectivity-agent/OIC-Connectivity-Agent-and-Hybrid-Integrations.pdf
please lower case the file name

Add in PDF the footer 'Public' as well.

2023-07-05 17:22 UTC, closed without merging