first_commit
oracle-devrel/technology-engineering pull request #631
Opened 2023-11-23 00:11 UTC by eugsim1

snmp okv utilty

2023-11-28 15:23 UTC, oheimburger requested changes
Remove the branch, hardcoded passwords are not allowed.

2023-11-28 15:23 UTC, oheimburger commented on manageability-and-operations/observability-and-manageability/okv-monitoring/files/main.go
> +			AuthenticationPassphrase: "Welcome123.",
No hardcoded passwords!

2023-11-28 15:23 UTC, oheimburger commented on manageability-and-operations/observability-and-manageability/okv-monitoring/files/main.go
> +			PrivacyPassphrase:        "Welcome123.",
No hardcoded passwords!

2023-11-28 19:48 UTC, eugsim1 reviewed
done

2023-11-29 11:00 UTC, eugsim1 commented
modification is done

2023-11-29 17:46 UTC, eugsim1 reviewed
please review the new commit with some update on monitoring scripts as well

2023-12-19 08:25 UTC, closed without merging