data-science-and-ml content update
oracle-devrel/technology-engineering pull request #658
Opened 2023-12-08 09:13 UTC by vatudorache

2023-12-11 11:08 UTC, AlexanderHodicke requested changes
Thanks for submitting this PR!

Please complete the following steps:
1:Review by @oheimburger needed
2: See my notes in some files
2.1: No copyright as everything needs to be under UPL
2.2: Links need to be descriptive in the README files
3: Please make sure to follow the right folder structure
3.1: All folders and files are named lower-case with - instead of white spaces, meaning 'Hello World.pdf' -> 'hello-world.pdf'
3.2: Make sure each asset has its own folder, with a README.md as per my template, a LICENSE file and a 'files' folder with the files for a single asset. Do not have a single folder and just put a lot of different files for different assets in one folder.
4: Possible legal review for AI content

2023-12-11 11:08 UTC, AlexanderHodicke commented on data-platform/data-science-and-ml/shared-assets/other-assets/Innovation with AI Machine Learning and Data Science.pdf
@vatudorache Copyright

2023-12-11 11:08 UTC, AlexanderHodicke commented on data-platform/data-science-and-ml/shared-assets/other-assets/OCI AI-ML-DS architecture templates.pdf
@vatudorache Copyright

2023-12-11 11:10 UTC, AlexanderHodicke commented
@vatudorache For your next PR. please try to keep them small and create individual PR for smaller changes or individual assets. One big bang could easily result in redoing the whole PR if we find any major errors.  Just FYI

2023-12-13 08:21 UTC, vatudorache commented on data-platform/data-science-and-ml/shared-assets/art-of-possibile-demo-assets/Procurement Forecasting/README.md
It is indeed called 'end-to-end' because this is consistent with other assets where we have multiple links for specific sections, and for that case the section descriptor is the title.

2023-12-13 08:22 UTC, vatudorache commented on data-platform/data-science-and-ml/shared-assets/art-of-possibile-demo-assets/Tax Fraud Detection/README.md
(Same as above. I believe everyone understands what 'end-to-end' means.)
It is indeed called 'end-to-end' because this is consistent with other assets where we have multiple links for specific sections, and for that case the section descriptor is the title.

2023-12-13 09:31 UTC, vatudorache commented on data-platform/data-science-and-ml/shared-assets/art-of-possibile-demo-assets/Footfall Forecasting/Footfall Forecasting.pdf
Corrected.

2023-12-13 09:34 UTC, vatudorache commented on data-platform/data-science-and-ml/shared-assets/art-of-possibile-demo-assets/Tax Fraud Detection/Tax Fraud Detection.pdf
Corrected.

2023-12-13 09:34 UTC, vatudorache commented on data-platform/data-science-and-ml/shared-assets/other-assets/Innovation with AI Machine Learning and Data Science.pdf
Corrected.

2023-12-14 05:44 UTC, vatudorache commented on data-platform/data-science-and-ml/shared-assets/art-of-possibile-demo-assets/Did-Not-Attend Risk Model/Did-Not-Attend Risk Model.pdf
Corrected.

2023-12-14 05:44 UTC, vatudorache commented on data-platform/data-science-and-ml/shared-assets/other-assets/OCI AI-ML-DS architecture templates.pdf
Corrected.

2023-12-19 08:46 UTC, oheimburger requested changes
This branch should be removed.
It violates the policy of not including default usernames and passwords.
Also some files have the user VALENTIN in there. Should be changed to a neutral username.

2023-12-19 08:46 UTC, oheimburger commented on data-platform/data-science-and-ml/oracle-data-science-service/code-assets/ods-mlflow.auth.demo.ipynb
> +    "os.environ['MLFLOW_TRACKING_USERNAME'] = 'admin'\n",
Policy violation. Username and password included.

2023-12-19 08:46 UTC, oheimburger commented on data-platform/data-science-and-ml/oracle-data-science-service/code-assets/ods-mlflow.auth.mysql.demo.ipynb
> +    "# Define Username and Password as ENV Variables\n",
Policy violation. Username and password included.

2023-12-19 10:39 UTC, oheimburger requested changes
Please fix the requested changes in the next PR.

2023-12-19 10:39 UTC, oheimburger commented on data-platform/data-science-and-ml/oracle-machine-learning/code-assets/oml-prepare.data.for.machine.learning.json
> +      "user": "VALENTIN",
User should be something generic. Do not use 'VALENTIN'.

2023-12-19 10:39 UTC, oheimburger commented on data-platform/data-science-and-ml/oracle-machine-learning/code-assets/oml-prepare.data.for.graph.json
> +      "user": "VALENTIN",
User should be generic. Do not use "VALENTIN". Applies to the whole file.

2023-12-19 10:39 UTC, oheimburger commented on data-platform/data-science-and-ml/oracle-machine-learning/code-assets/oml-explore.enhanced.data.json
> +      "user": "VALENTIN",
User should not be a generic username. Do not use "VALENTIN". Many locations in this file.

2023-12-19 10:39 UTC, oheimburger commented on data-platform/data-science-and-ml/oracle-machine-learning/code-assets/oml-create.machine.learning.models.json
> +      "user": "VALENTIN",
User should not be a generic username. Do not use "VALENTIN". Many locations in this file.

2023-12-19 10:39 UTC, oheimburger commented on data-platform/data-science-and-ml/shared-assets/other-assets/RStudio-install-on-Oracle-Linux.pdf
Copyright missing.

2023-12-19 10:39 UTC, oheimburger commented on data-platform/data-science-and-ml/shared-assets/other-assets/OCI-AI-ML-DS-architecture-templates.pdf
Copyright missing.

2023-12-19 10:39 UTC, oheimburger commented on data-platform/data-science-and-ml/shared-assets/other-assets/Innovation-with-AI-Machine-Learning-and-Data-Science.pdf
Copyright missing.

2023-12-19 10:39 UTC, oheimburger commented on data-platform/data-science-and-ml/shared-assets/art-of-possibile-demo-assets/Tax-Fraud-Detection/Tax-Fraud-Detection.pdf
Copyright missing.

2023-12-19 10:39 UTC, oheimburger commented on data-platform/data-science-and-ml/shared-assets/art-of-possibile-demo-assets/Procurement-Forecasting/Procurement-Forecasting.pdf
Copyright missing.

2023-12-19 10:39 UTC, oheimburger commented on data-platform/data-science-and-ml/shared-assets/art-of-possibile-demo-assets/Footfall-Forecasting/Footfall-Forecasting.pdf
Copyright missing.

2023-12-19 10:39 UTC, oheimburger commented on data-platform/data-science-and-ml/shared-assets/art-of-possibile-demo-assets/Did-Not-Attend-Risk-Model/Did-Not-Attend-Risk-Model.pdf
Copyright missing.

2023-12-19 10:39 UTC, oheimburger commented on data-platform/data-science-and-ml/oracle-machine-learning/OML4R-installation-on-Oracle-Database.pdf
Copyright missing.

2023-12-19 10:39 UTC, oheimburger commented on data-platform/data-science-and-ml/oracle-data-science-service/R-Conda-environment-installation-for-OCI-Data-Science.pdf
Copyright missing.

2023-12-19 10:39 UTC, oheimburger commented on data-platform/data-science-and-ml/oracle-data-science-service/Provisioning-OCI-AI-all-in-one-Data-Science-image.pdf
Copyright missing.

2023-12-19 10:39 UTC, oheimburger commented on data-platform/data-science-and-ml/oracle-data-science-service/OCI-setup-MLFlow-tracking-server.pdf
Copyright missing.

2023-12-19 10:39 UTC, oheimburger commented on data-platform/data-science-and-ml/oracle-data-science-service/Jobs-with-OCI-Data-Science-ADS-Operator-Control.pdf
Copyright missing.

2023-12-19 10:39 UTC, oheimburger commented on data-platform/data-science-and-ml/oracle-data-science-service/Jobs-for-distributed-training-with-OCI-Data-Science.pdf
Copyright missing.

2023-12-19 10:39 UTC, oheimburger commented on data-platform/data-science-and-ml/oracle-data-science-service/GitHub-integration-for-OCI-Data-Science.pdf
Copyright missing.

2023-12-19 13:37 UTC, closed without merging