lift-mysql-discovery-script
oracle-devrel/technology-engineering pull request #74
Opened 2023-06-30 03:40 UTC by Soumyadeep-Oracle

2023-06-30 13:34 UTC, AlexanderHodicke requested changes

2023-06-30 13:34 UTC, AlexanderHodicke commented on cloud-architecture/custom-apps-and-consolidation/mysql-discovery-utility/files/MySQLdiscovery.sh
@oheimburger code review

2023-06-30 14:28 UTC, oheimburger commented on cloud-architecture/custom-apps-and-consolidation/mysql-discovery-utility/README.md
> +MySQL Database Discovery & Analysis Utility is a discovery utility to fetch the database information and the host details. In order to capture complete details of the source MySQL instance, the disco
Replace '&' with 'and'.

2023-07-03 07:31 UTC, Soumyadeep-Oracle commented on cloud-architecture/custom-apps-and-consolidation/mysql-discovery-utility/README.md
> +MySQL Database Discovery & Analysis Utility is a discovery utility to fetch the database information and the host details. In order to capture complete details of the source MySQL instance, the disco
Submitted with required changes.

2023-07-03 07:31 UTC, Soumyadeep-Oracle commented on cloud-architecture/custom-apps-and-consolidation/mysql-discovery-utility/files/MySQLdiscovery.sh
> +#!/bin/bash
Submitted with required changes.

2023-07-03 10:03 UTC, oheimburger commented on cloud-architecture/custom-apps-and-consolidation/oracle-db-consolidation/db-discovery/discovery-utility/LICENSE
What is this file for?

2023-07-03 10:13 UTC, Soumyadeep-Oracle commented on cloud-architecture/custom-apps-and-consolidation/oracle-db-consolidation/db-discovery/discovery-utility/LICENSE
This LICENSE file was missing for an earlier asset uploaded. The asset location was discovery-utility/files. As the LICENSE was missed earlier, uploaded the same to correct the same.

2023-07-04 12:32 UTC, AlexanderHodicke approved these changes

2023-07-04 12:32 UTC, merged