Lvbirgelen initial bastion session script
oracle-devrel/technology-engineering pull request #8
Opened 2023-06-27 09:28 UTC by lvbirgelen

2023-06-27 09:32 UTC, lvbirgelen commented
I have read the CLA Document and I hereby sign the CLA

2023-06-28 10:08 UTC, AlexanderHodicke requested changes
please move the file and @oheimburger code review

2023-06-28 10:08 UTC, AlexanderHodicke commented on security/security-design/bastion-session-script/bastion-session.sh
> +#!/usr/bin/env bash
Please move this file to a subfolder called /files

@oheimburger code review please

2023-06-28 14:46 UTC, merged

2023-07-04 08:08 UTC, lvbirgelen commented on security/security-design/bastion-session-script/bastion-session.sh
> +#!/usr/bin/env bash
For portability its considered better to use the original:
https://en.wikipedia.org/wiki/Shebang_(Unix)#Portability