Azure devops oke
oracle-devrel/technology-engineering pull request #821
Opened 2024-02-12 16:29 UTC by mikarinneoracle

Azure DevOps build and deploy to OKE repo added

2024-02-12 21:58 UTC, martatolosa requested changes
add this at the end of readme.md

License
Copyright (c) 2024 Oracle and/or its affiliates.

Licensed under the Universal Permissive License (UPL), Version 1.0.

See [LICENSE](https://github.com/oracle-devrel/technology-engineering/blob/main/LICENSE) for more details.

2024-02-13 04:48 UTC, mikarinneoracle commented
> add this at the end of readme.md
> 
> License Copyright (c) 2024 Oracle and/or its affiliates.
> 
> Licensed under the Universal Permissive License (UPL), Version 1.0.
> 
> See [LICENSE](https://github.com/oracle-devrel/technology-engineering/blob/main/LICENSE) for more details.

Added! :)

2024-02-13 08:50 UTC, martatolosa commented
closing

2024-02-13 08:52 UTC, martatolosa approved these changes

2024-02-13 08:52 UTC, merged