Mission critical phase1
oracle-devrel/technology-engineering pull request #84
Opened 2023-06-30 09:15 UTC by Mramcha

Just added all README.mds with some links.

2023-06-30 09:25 UTC, Mramcha commented
I have read the CLA Document and I hereby sign the CLA

2023-06-30 09:25 UTC, Mramcha commented
recheck

2023-06-30 13:23 UTC, AlexanderHodicke requested changes

2023-06-30 13:23 UTC, AlexanderHodicke commented on data-platform/mission-critical-database/Disaster Recovery/README.md
disaster-recovery folder name

2023-06-30 13:23 UTC, AlexanderHodicke commented on data-platform/mission-critical-database/High Availability/README.md
high-availability

2023-06-30 15:32 UTC, Mramcha commented
recheck

2023-06-30 15:32 UTC, Mramcha commented on data-platform/mission-critical-database/High Availability/README.md
done

2023-06-30 15:32 UTC, Mramcha commented on data-platform/mission-critical-database/Disaster Recovery/README.md
done

2023-06-30 15:32 UTC, Mramcha commented on data-platform/mission-critical-database/Data Protection/README.md
done.

2023-07-03 10:29 UTC, AlexanderHodicke approved these changes

2023-07-03 10:30 UTC, merged