lift-analytics-Maps using Json files
oracle-devrel/technology-engineering pull request #86
Opened 2023-06-30 09:22 UTC by Soumyadeep-Oracle

2023-06-30 13:58 UTC, AlexanderHodicke requested changes

2023-06-30 13:58 UTC, AlexanderHodicke commented on data-platform/analytics/oac-map-extensions/fles/Geo Json Files.zip
@oheimburger can you have a look at the geo JSON stuff

2023-06-30 14:26 UTC, oheimburger commented
Whare are the GeoJSON files from? Is there a Copyright?

2023-06-30 14:27 UTC, oheimburger commented
The files in the directory `fles` should be moved to `files`. Directory `fles` should be removed.

2023-07-04 11:06 UTC, Soumyadeep-Oracle commented
> Whare are the GeoJSON files from? Is there a Copyright?

These geo jsons have been taken as a sample from d3 and modified according to our requirements for different countries.
D3 is a free tool available.

2023-07-18 13:03 UTC, oheimburger requested changes

2023-07-19 06:57 UTC, Soumyadeep-Oracle commented
Changes done.

From: oheimburger ***@***.***>
Date: Tuesday, 18 July 2023 at 6:33 PM
To: oracle-devrel/technology-engineering ***@***.***>
Cc: Soumyadeep Mitra ***@***.***>, Author ***@***.***>
Subject: [External] : Re: [oracle-devrel/technology-engineering] lift-analytics-Maps using Json files (PR #86)

@oheimburger requested changes on this pull request.

________________________________

On data-platform/analytics/oac-map-extensions/THIRD_PART_LICENSES<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/86*discussion_r1266742454__;Iw!!ACWV5N9M2RV99hQ!LEyW4IPyCTGIMTo2wa2ChJkPQRjVc1ffNBP43gN91gzAMt8-Zi1oLCIn2VMxkqlif6bMLi-A_-aj54QtGu-eblUdyMMnCA$>:

Change this file name to 'THIRD_PARTY_LICENSES'.

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/86*pullrequestreview-1534987878__;Iw!!ACWV5N9M2RV99hQ!LEyW4IPyCTGIMTo2wa2ChJkPQRjVc1ffNBP43gN91gzAMt8-Zi1oLCIn2VMxkqlif6bMLi-A_-aj54QtGu-eblWKsDJkLw$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/A76TVZM4X62TOS7IWDBZ6HLXQ2CSFANCNFSM6AAAAAAZZS4II4__;!!ACWV5N9M2RV99hQ!LEyW4IPyCTGIMTo2wa2ChJkPQRjVc1ffNBP43gN91gzAMt8-Zi1oLCIn2VMxkqlif6bMLi-A_-aj54QtGu-eblXpFj3JkA$>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-07-21 10:37 UTC, oheimburger submitted a review, later dismissed

2023-09-20 07:57 UTC, AlexanderHodicke approved these changes

2023-09-20 07:57 UTC, merged