Eugene
oracle-devrel/technology-engineering pull request #876
Opened 2024-03-01 14:30 UTC by eugsim1

taggin script

2024-03-01 14:46 UTC, mfioramo reviewed
approving from my side. Olaf need to review before merging

2024-03-01 14:50 UTC, mfioramo submitted a review, later dismissed

2024-03-07 12:36 UTC, oheimburger requested changes

2024-03-07 13:17 UTC, eugsim1 commented on manageability-and-operations/operations-advisory/oci-operation/tagging/README.md.saved.bak
Hi you should update the .gitgnore base file to avoid this issue 
i have copied this branch in my local repo i dont see the *.bak
Can you please update the .gitgnore to be sure that we are getting something conformant to your policies ?
Thanks

2024-03-07 13:31 UTC, oheimburger commented on manageability-and-operations/operations-advisory/oci-operation/tagging/README.md.saved.bak
.gitignore is a local file not uploaded (pushed) to the github repo. Please make sure that your local changes have been pushed to github.
Thank you.

2024-03-07 13:34 UTC, eugsim1 commented on manageability-and-operations/operations-advisory/oci-operation/tagging/README.md.saved.bak
There is a global .gitgnore this one has to be updated , otherwise why there is such a file in the repository root ?

2024-03-07 14:02 UTC, eugsim1 commented
We dont see this file any more

2024-03-15 08:00 UTC, oheimburger requested changes

2024-10-02 12:29 UTC, closed without merging